project_name: evaluate-resource-action
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
builds:
  - env:
    # - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
dockers:
  - image_templates:
      - "ghcr.io/rode/evaluate-resource-action:latest"
      - "ghcr.io/rode/evaluate-resource-action:{{ .Tag }}"
      - "ghcr.io/rode/evaluate-resource-action:v{{ .Major }}"
      - "ghcr.io/rode/evaluate-resource-action:v{{ .Major }}.{{ .Minor }}"
    extra_files:
      - "go.mod"
      - "go.sum"
      - "main.go"
      - "config"
      - "action"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
