name: evaluate-policy
author: rode@liatrio.com
description: Evaluates a resource against a policy group
branding:
  icon: anchor
  color: green

runs:
  using: docker
  image: Dockerfile
  env:
    ACCESS_TOKEN: ${{ inputs.accessToken }}
    ENFORCE: ${{ inputs.enforce }}
    POLICY_GROUP: ${{ inputs.policyGroup }}
    RESOURCE_URI: ${{ inputs.resourceUri }}
    RODE_HOST: ${{ inputs.rodeHost }}
    RODE_INSECURE_DISABLE_TRANSPORT_SECURITY: ${{ inputs.rodeInsecure }}

inputs:
  accessToken:
    description: "An access token that will be included in requests to Rode."
    required: false
  enforce:
    description: "Controls whether the step should fail if the evaluation fails."
    required: true
    default: "true"
  policyGroup:
    description: "The policy group to evaluate the resource against."
    required: true
    default: ""
  resourceUri:
    description: "The resource to evaluate policy against."
    required: true
  rodeHost:
    description: "Hostname of the Rode instance"
    required: true
  rodeInsecure:
    description: "Disables transport security when communicating with Rode."
    required: true
    default: "false"

outputs:
  pass:
    description: Whether the resource passed evaluation
